/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.com.taiji;

import com.google.common.base.Splitter;
import org.apache.commons.lang3.StringUtils;
import java.util.regex.Pattern;

public class App {
    public static void main(String[] args) {
        String  s = "abc;def\\;123";
        System.out.println(s);
        String[] array = s.split("\\{1};");
        for (String  ss: array) {
            System.out.println(ss);
        }

        Iterable<String> items = Splitter.on(Pattern.compile("[\\;:-]")).split(s);
        for (String ss: items) {
            System.out.println(ss);
        }

        String[] arr2 = StringUtils.split(s, ";:-");
        for (String ss: arr2) {
            System.out.println(ss);
        }

    }
}
